import * as React from "react";
import * as Types from "./types";

declare function PropertyCard(props: {
  as?: React.ElementType;
  secoundLine?: React.ReactNode;
  accoladeImageDispaly?: Types.Visibility.VisibilityConditions;
  accoladeIcon?: Types.Asset.Image;
  imageAccoladeAltText?: Types.Basic.AltText;
  acolladeFavoriteTag?: Types.Basic.TagType;
  imageSlot?: Types.Devlink.Slot;
  runtimeProp?: Types.Devlink.RuntimeProps;
  cardLink?: Types.Basic.TagType;
  slug?: Types.Builtin.Text;
  locationCity?: Types.Builtin.Text;
  locationState?: Types.Builtin.Text;
  locationZip?: Types.Builtin.Text;
  locationDataAddress?: Types.Builtin.Text;
  locationDataLng?: Types.Builtin.Text;
  locationPropertyTitle?: React.ReactNode;
  locationDataLat?: Types.Builtin.Text;
  locationStateSmall?: React.ReactNode;
  locationCitySmall?: React.ReactNode;
  propertyListingsNumberOfGuest?: React.ReactNode;
  propertyListingsNumberOfBedrooms?: React.ReactNode;
  propertyListingsNumberOfBathrooms?: React.ReactNode;
  propertyDurationDuration?: React.ReactNode;
  /** Price*/
  propertyPriceMonthlyPrice?: React.ReactNode;
  propertyPriceMonthlyComparedPrice?: React.ReactNode;
  propertyReviewNumberOfReviews?: React.ReactNode;
  propertyReviewPropertyRating?: React.ReactNode;
  hostAccoladesPlusHost?: React.ReactNode;
  hostAccoladesSuperHost?: React.ReactNode;
  hostAccoladesVerifiedHost?: React.ReactNode;
  hostAccoladesSuperHostOn?: Types.Visibility.VisibilityConditions;
  hostAccoladesPropertyAccoladeVIsiblitOn?: Types.Visibility.VisibilityConditions;
  hostAccoladesPlusHostVIsibility?: Types.Visibility.VisibilityConditions;
  hostAccoladesVerifiedHostOn?: Types.Visibility.VisibilityConditions;
  hostAccoladesPremiumHostOn?: Types.Visibility.VisibilityConditions;
  propertyImageImage1?: Types.Asset.Image;
  propertyImageImage2?: Types.Asset.Image;
  propertyImageImage3?: Types.Asset.Image;
  propertyImageImage4?: Types.Asset.Image;
  propertyImageImage5?: Types.Asset.Image;
  variant?: "Base" | "Popup";
  propertyLinkPropertyLink?: Types.Basic.Link;
  onClick?: Types.Devlink.RuntimeProps;
  ratingVisibility?: Types.Visibility.VisibilityConditions;
  visibility2ndLine?: Types.Visibility.VisibilityConditions;
  visibility4thLine?: Types.Visibility.VisibilityConditions;
  visibility3rdLine?: Types.Visibility.VisibilityConditions;
  visibility1stLine?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
