name = "easystay-retreats-webflow-cloud"
main = ".cloudflare/worker.js"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]

[vars]
BASE_PATH = "/app"
ASSETS_PREFIX = "/app"
BASE_URL = "https://your-site.webflow.io"

[env.production.vars]
BASE_URL = "https://your-site.webflow.io"
