name = "easystayretreats-app"
main = ".cloudflare/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "easystayretreats-app"

[env.staging]
name = "easystayretreats-app-staging"

[[env.production.vars]]
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""
GOOGLE_MAPS_API_KEY = ""

[[env.staging.vars]]
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""
GOOGLE_MAPS_API_KEY = ""
