import type { Property, PropertySearchResponse } from "@/lib/types";

export const mockProperties: Property[] = [
  {
    id: "sample-1",
    slug: "modern-villa-miami",
    name: "Modern Villa in Miami",
    shortDescription: "Luxury villa with private pool, outdoor kitchen, and walkable beach access.",
    nightlyPrice: 486,
    rating: 4.9,
    reviewCount: 128,
    guestCapacity: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 3,
    isSuperHost: true,
    heroImageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80",
    city: "Miami",
    state: "Florida",
    country: "United States",
    latitude: 25.790654,
    longitude: -80.1300455,
    addressLine1: "123 Ocean Drive",
    addressLine2: null
  },
  {
    id: "sample-2",
    slug: "hudson-river-loft",
    name: "Hudson River Loft",
    shortDescription: "Glass-wrapped loft with sweeping river views and private workstation.",
    nightlyPrice: 362,
    rating: 4.8,
    reviewCount: 96,
    guestCapacity: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    isSuperHost: true,
    heroImageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80",
    city: "New York",
    state: "New York",
    country: "United States",
    latitude: 40.721786,
    longitude: -74.009447,
    addressLine1: "250 Hudson Street",
    addressLine2: null
  },
  {
    id: "sample-3",
    slug: "desert-dunes-retreat",
    name: "Desert Dunes Retreat",
    shortDescription: "Stargazer-friendly escape with plunge pool and outdoor fire bowls in Scottsdale.",
    nightlyPrice: 274,
    rating: 4.85,
    reviewCount: 64,
    guestCapacity: 5,
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    isSuperHost: false,
    heroImageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80",
    city: "Scottsdale",
    state: "Arizona",
    country: "United States",
    latitude: 33.494171,
    longitude: -111.926048,
    addressLine1: "88 Desert Bloom",
    addressLine2: null
  },
  {
    id: "sample-4",
    slug: "napa-vineyard-cottage",
    name: "Napa Vineyard Cottage",
    shortDescription: "Charming cottage tucked among vineyards with tasting room and bikes included.",
    nightlyPrice: 418,
    rating: 5,
    reviewCount: 45,
    guestCapacity: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    isSuperHost: false,
    heroImageUrl: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1600&q=80",
    city: "Napa",
    state: "California",
    country: "United States",
    latitude: 38.297538,
    longitude: -122.286865,
    addressLine1: "12 Vineyard Lane",
    addressLine2: null
  }
];

export const mockResponse: PropertySearchResponse = {
  properties: mockProperties,
  total: mockProperties.length
};
